export const PERFORMANCE_CONSTANTS = {
  MIN_UNIQUE_QUESTIONS_FOR_CLASSIFICATION: 5,
  MIN_UNIQUE_QUESTIONS_FOR_STRONG: 10,
  WEAK_ACCURACY_THRESHOLD: 50.0,
  STRONG_ACCURACY_THRESHOLD: 80.0,
  RECENT_EVENTS_WINDOW_SIZE: 20,
  
  PRIORITY_WEIGHTS: {
    RECENT_WRONG: 0.60,
    LATEST_UNIQUE_WRONG: 0.25,
    REPEATED_ERROR: 0.15,
  },
};
