export const INITIAL_ROLES = [
  {
    name: 'Super Admin',
    description: 'Full administrative access across all system resources and team configurations.',
  },
  {
    name: 'Content Manager',
    description: 'Management access for Study Materials, MCQ Library, Current Affairs, Quick Revision, and Exam draft creation.',
  },
  {
    name: 'Content Reviewer',
    description: 'Review and approval access for submitted study materials, MCQs, and exam cycles.',
  },
  {
    name: 'Support Executive',
    description: 'Customer support, student inquiry resolution, and subscription management support.',
  },
];

export const INITIAL_PERMISSIONS = [
  { code: 'dashboard.view', name: 'View Admin Dashboard', description: 'Access main administration dashboard overview' },
  { code: 'exams.view', name: 'View Exams Module', description: 'View competitive exam configurations' },
  { code: 'exams.create', name: 'Create Exams', description: 'Create draft exam cycles' },
  { code: 'exams.update', name: 'Update Exams', description: 'Update draft exam cycle details' },
  { code: 'exams.submit_review', name: 'Submit Exams for Review', description: 'Submit draft exam cycles for editorial review' },
  { code: 'exams.review', name: 'Review Exams', description: 'Review submitted exam cycles' },
  { code: 'exams.approve', name: 'Approve Exams', description: 'Approve reviewed exam cycles' },
  { code: 'exams.publish', name: 'Publish Exams', description: 'Publish approved exam cycles to public portal' },
  { code: 'exams.close', name: 'Close Exams', description: 'Close completed exam cycles' },
  { code: 'exams.archive', name: 'Archive Exams', description: 'Archive obsolete exam cycles' },
  { code: 'exams.authorities.manage', name: 'Manage Exam Authorities', description: 'Create and manage conducting exam authorities' },
  { code: 'exams.programmes.manage', name: 'Manage Exam Programmes', description: 'Create and manage exam programmes' },
  { code: 'exams.stages.manage', name: 'Manage Exam Stages', description: 'Create and manage exam stage configurations' },
  { code: 'exams.papers.manage', name: 'Manage Exam Papers', description: 'Create and manage exam papers and negative marking rules' },
  { code: 'exams.pattern.manage', name: 'Manage Exam Patterns', description: 'Build, review, approve, and publish exam patterns and revisions' },
  { code: 'exams.syllabus.manage', name: 'Manage Exam Syllabus', description: 'Create, build, review, approve, publish, and clone versioned exam syllabus trees' },
  { code: 'exams.analytics.view', name: 'View Exam Analytics', description: 'View exam portfolio analytics, readiness diagnostics, workflow queues, and important dates' },
  { code: 'study_materials.view', name: 'View Study Materials', description: 'View and manage study notes and syllabus modules' },
  { code: 'mcq_tests.view', name: 'View MCQ Library & Tests', description: 'View question banks and mock tests' },
  { code: 'study_plans.view', name: 'View Study Plans', description: 'View student study schedules and planning rules' },
  { code: 'students.view', name: 'View Students List', description: 'View non-sensitive student registration lists' },
  { code: 'current_affairs.view', name: 'View Current Affairs', description: 'View daily and monthly Karnataka current affairs' },
  { code: 'quick_revision.view', name: 'View Quick Revision', description: 'View flashcards and rapid recall notes' },
  { code: 'subscriptions_payments.view', name: 'View Subscriptions & Payments', description: 'View payment histories and active student passes' },
  { code: 'team.view', name: 'View Team Members', description: 'View administrative team member profiles' },
  { code: 'support.view', name: 'View Support Tickets', description: 'View student support inquiries and tickets' },
  { code: 'settings.view', name: 'View System Settings', description: 'View system configurations' },
  { code: 'students.sensitive_dob.view', name: 'View Student Date of Birth', description: 'View student sensitive date of birth field' },
  { code: 'students.sensitive_guardian.view', name: 'View Student Guardian Info', description: 'View under-18 guardian contact and consent details' },
  { code: 'auth.sessions.view', name: 'View Active Sessions', description: 'View active administrator device sessions' },
  { code: 'auth.sessions.revoke', name: 'Revoke Device Sessions', description: 'Revoke active web or mobile authentication sessions' },
  { code: 'admin.roles.view', name: 'View Roles and Permissions', description: 'View role permission matrices' },
  { code: 'admin.roles.manage', name: 'Manage System Roles', description: 'Assign or modify administrative roles' },
  { code: 'audit_logs.view', name: 'View Audit Trail', description: 'View system and security audit logs' },
  { code: 'academic_taxonomy.manage', name: 'Manage Academic Taxonomy', description: 'Create, edit, reorder, move, activate, deactivate, and manage academic taxonomy hierarchy' },
  { code: 'study_materials.create', name: 'Create Study Materials', description: 'Create canonical study material records and English/Kannada draft locales' },
  { code: 'study_materials.update', name: 'Update Study Materials', description: 'Update canonical study material details, draft locales, and taxonomy mappings' },
  { code: 'study_materials.archive', name: 'Archive Study Materials', description: 'Archive and restore canonical study material records' },
  { code: 'study_materials.delete_draft', name: 'Delete Draft Study Materials', description: 'Delete eligible draft study material records' },
  { code: 'study_materials.submit_review', name: 'Submit Study Materials for Review', description: 'Submit draft locale revisions for editorial review' },
  { code: 'study_materials.review', name: 'Review Study Materials', description: 'Review submitted study material locale revisions' },
  { code: 'study_materials.approve', name: 'Approve Study Materials', description: 'Approve reviewed study material locale revisions' },
  { code: 'study_materials.publish', name: 'Publish Study Materials', description: 'Publish approved study material locale revisions' },
  { code: 'study_materials.access.manage', name: 'Manage Study Material Access', description: 'Manage Study Material commercial access policies, paywalls, and freemium boundaries' },
  { code: 'study_materials.access.preview', name: 'Preview Study Material Access', description: 'Preview Study Material commercial access states, paywalls, and boundary previews' },
  { code: 'study_materials.access.override', name: 'Override Study Material Access', description: 'Override Study Material commercial access rules for administrative testing' },
  { code: 'mcq.view', name: 'View MCQ Question Bank', description: 'View MCQ questions and question bank dashboard' },
  { code: 'mcq.create', name: 'Create MCQ Questions', description: 'Create draft bilingual MCQ questions' },
  { code: 'mcq.edit', name: 'Edit MCQ Questions', description: 'Edit draft and submitted MCQ questions' },
  { code: 'mcq.submit_review', name: 'Submit MCQ Questions for Review', description: 'Submit draft MCQ questions for editorial review' },
  { code: 'mcq.review', name: 'Review MCQ Questions', description: 'Review submitted MCQ questions and request changes' },
  { code: 'mcq.approve', name: 'Approve MCQ Questions', description: 'Approve reviewed MCQ questions for test eligibility' },
  { code: 'mcq.archive', name: 'Archive MCQ Questions', description: 'Archive obsolete or deprecated MCQ questions' },
];

export const ROLE_PERMISSION_MAPPINGS: Record<string, string[]> = {
  'Super Admin': INITIAL_PERMISSIONS.map((p) => p.code),
  'Content Manager': [
    'dashboard.view',
    'exams.view',
    'exams.create',
    'exams.update',
    'exams.submit_review',
    'exams.authorities.manage',
    'exams.programmes.manage',
    'exams.stages.manage',
    'exams.papers.manage',
    'exams.pattern.manage',
    'exams.syllabus.manage',
    'exams.analytics.view',
    'study_materials.view',
    'academic_taxonomy.manage',
    'study_materials.create',
    'study_materials.update',
    'study_materials.archive',
    'study_materials.delete_draft',
    'study_materials.submit_review',
    'study_materials.access.manage',
    'study_materials.access.preview',
    'mcq_tests.view',
    'mcq.view',
    'mcq.create',
    'mcq.edit',
    'mcq.submit_review',
    'study_plans.view',
    'current_affairs.view',
    'quick_revision.view',
  ],
  'Content Reviewer': [
    'dashboard.view',
    'exams.view',
    'exams.review',
    'exams.approve',
    'exams.analytics.view',
    'study_materials.view',
    'study_materials.review',
    'study_materials.approve',
    'study_materials.access.preview',
    'mcq.view',
    'mcq.review',
    'mcq.approve',
  ],
  'Support Executive': ['dashboard.view', 'students.view', 'subscriptions_payments.view', 'support.view'],
};
